---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: kafka
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: kunalbagwe/consumer:latest
        #        ports:
        #- containerPort: 8080
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: http-service
#  namespace: kafka
#spec:
#  selector:
#    app: http
#  ports:
#    - protocol: TCP
#      port: 8080
#      targetPort: 8080

