name: Integration Test Suite WorkFlow

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v1
      - name: Clone the fission repository
        run: |
          git clone https://github.com/fission/keda-connectors.git
      - name: Install Tool
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/bin/
      - name: Run Kind Cluster
        run: |
          ./registry.sh
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          kubectl create namespace keda
          helm install keda kedacore/keda --namespace keda
      - name: Create Docker Image for HTTP server
        run: |
          cd server/
          docker build -t localhost:5000/http-server:latest .
          docker push localhost:5000/http-server:latest
      - name: Create Docker Image for KEDA Connector
        run: |
          cd keda-connectors/kafka-http-connector/
          docker build -t localhost:5000/kafka-connector:latest .
          docker push localhost:5000/kafka-connector:latest
      - name: Create Docker Image for Consumer
        run: |
          cd consumer/
          docker build -t localhost:5000/consumer:latest .
          docker push localhost:5000/consumer:latest
      - name: Deploy Kafka cluster
        run: |
          cd kafka/
          kubectl create namespace kafka
          curl -L http://strimzi.io/install/latest | sed 's/namespace: .*/namespace: kafka/' | kubectl apply -f - -n kafka
          sleep 5s
          kubectl apply -f kafka-cluster.yaml
          echo "Kafka Cluster is getting up."
          # sleep 10m
          kubectl wait -f kafka-cluster.yaml --for=condition=ready --timeout=-1s -n kafka
      - name: Create Kafka topics
        run: |
          cd kafka/
          kubectl apply -f kafka-req-topic.yaml 
          kubectl apply -f kafka-err-topic.yaml
          kubectl apply -f kafka-res-topic.yaml
      - name: Produce messages
        run: |
          cd kafka/
          kubectl apply -f kafka-producer.yaml
          kubectl wait -f kafka-producer.yaml --for=condition=ready --timeout=-1s -n kafka
      - name: Bring up HTTP Server
        run: |
          cd server/
          kubectl apply -f server.yaml
      - name: Deploy Keda Connector and Keda ScaledObject
        run: |
          cd kafka/ 
          kubectl apply -f keda-deployment.yml
          kubectl apply -f Keda-ScaledObj.yml 
      - name: Deploy Kafka consumer func and consumer deployment
        run: |
          cd consumer/
          kubectl apply -f consumer.yaml
          kubectl wait -f consumer.yaml --for=condition=ready --timeout=-1s -n kafka
          kubectl logs -l app=consumer --all-containers=true -f
