name: Shell Commands

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  integration-test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v1
      - name: Checkout the fission repo
        uses: action/checkout@v1
        with:
          repository: fission/keda-connectors 
          path: main
      - name: List dir
        run: |
          pwd
          ls 
      - name: Install Tools
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/bin/
      - name: Run Kind Cluster
        run: |
          bash registry.sh
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          kubectl create namespace keda
          helm install keda kedacore/keda --namespace keda
      - name: Check status
        run: kubectl wait --for=condition=Ready pods --all -n keda

#      - name: Test deployment
#        run: |
#          cd server/
#          docker build -t localhost:5000/http-server:latest .
#          docker push localhost:5000/http-server:latest

