name: Integration Test Suite WorkFlow
on:
  pull_request:
    types: [ labeled ]
jobs:
  test:
    if: ${{ github.event.label.name == 'rabbitmq' }} || ${{ github.event.label.name == 'RABBITMQ' }} || ${{ github.event.label.name == 'RabbitMQ' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: |
          echo "Hello World"
