name: Integration Test Suite WorkFlow
on:
  pull_request:
    branches:
      - master          
    types: [ labeled ]
jobs:
  test:
    if: "contains(github.event.pull_request.labels.*.name, 'rabbitmq')" || "contains(github.event.pull_request.labels.*.name, 'RABBITMQ')" "contains(github.event.pull_request.labels.*.name, 'RabbitMQ')"
    #if: ${{ github.event.label.name == 'rabbitmq' }} || ${{ github.event.label.name == 'RABBITMQ' }} || ${{ github.event.label.name == 'RabbitMQ' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: |
          echo "Hello World"
